In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

ModuleNotFoundError: No module named 'api_keys'

In [40]:
csv_path_1 = os.path.join("chi_school_2011_2012.csv")
schools_2011_df = pd.read_csv(csv_path_1, encoding="utf-8")
schools_2011_df.head()

,School ID,Name of School,"Elementary, Middle, or High School",Street Address,City,State,ZIP Code,Phone Number,Link,Network Manager,...,RCDTS Code,X_COORDINATE,Y_COORDINATE,Latitude,Longitude,Community Area Number,Community Area Name,Ward,Police District,Location
0,609966,Charles G Hammond Elementary School,ES,2819 W 21st Pl,Chicago,IL,60623,(773) 535-4580,http://schoolreports.cps.edu/SchoolProgressRep...,Pilsen-Little Village Elementary Network,...,150000000000000,1157809.015,1889554.623,41.852691,-87.696278,30,SOUTH LAWNDALE,12,10,"(41.85269133, -87.69627777)"
1,610539,Marvin Camras Elementary School,ES,3000 N Mango Ave,Chicago,IL,60634,(773) 534-2960,http://schoolreports.cps.edu/SchoolProgressRep...,Fullerton Elementary Network,...,150000000000000,1137482.296,1919394.900,41.934966,-87.770165,19,BELMONT CRAGIN,30,25,"(41.93496641, -87.77016525)"
2,609852,Eliza Chappell Elementary School,ES,2135 W Foster Ave,Chicago,IL,60625,(773) 534-2390,http://schoolreports.cps.edu/SchoolProgressRep...,Ravenswood-Ridge Elementary Network,...,150000000000000,1161016.902,1934466.545,41.975867,-87.683254,4,LINCOLN SQUARE,47,20,"(41.975867, -87.68325438)"
3,609835,Daniel R Cameron Elementary School,ES,1234 N Monticello Ave,Chicago,IL,60651,(773) 534-4290,http://schoolreports.cps.edu/SchoolProgressRep...,Garfield-Humboldt Elementary Network,...,150000000000000,1151767.546,1908130.068,41.903785,-87.717963,23,HUMBOLDT PARK,26,25,"(41.90378521, -87.71796315)"
4,610521,Sir Miles Davis Magnet Elementary Academy,ES,6730 S Paulina St,Chicago,IL,60636,(773) 535-9120,http://schoolreports.cps.edu/SchoolProgressRep...,Englewood-Gresham Elementary Network,...,150000000000000,1166133.893,1859929.018,41.771222,-87.666567,67,WEST ENGLEWOOD,15,7,"(41.77122181, -87.66656657)"

In [41]:
#schools_2011_df.columns

In [42]:
schools_2011_df = schools_2011_df[['School ID','Name of School','ZIP Code','Elementary, Middle, or High School','Graduation Rate %', 'Ward','Average Student Attendance']]
schools_2011_df

,School ID,Name of School,ZIP Code,"Elementary, Middle, or High School",Graduation Rate %,Ward,Average Student Attendance
0,609966,Charles G Hammond Elementary School,60623,ES,NDA,12,95.3
1,610539,Marvin Camras Elementary School,60634,ES,NDA,30,95.1
2,609852,Eliza Chappell Elementary School,60625,ES,NDA,47,95.1
3,609835,Daniel R Cameron Elementary School,60651,ES,NDA,26,92.6
4,610521,Sir Miles Davis Magnet Elementary Academy,60636,ES,NDA,15,93.0
...,...,...,...,...,...,...,...
561,610506,TEAM Englewood Community Academy High School,60621,HS,NDA,20,87.3
562,610350,Robert A Black Magnet Elementary School,60619,ES,NDA,8,96.0
563,610154,Martin A Ryerson Elementary School,60624,ES,NDA,27,95.5
564,610384,Infinity Math Science and Technology High School,60623,HS,84.4,22,92.2
565,609870,Daniel J Corkery Elementary School,60623,ES,NDA,22,94.7

In [43]:
schools_2011_df = schools_2011_df[schools_2011_df['Elementary, Middle, or High School'] == "HS"]
schools_2011_df = schools_2011_df[['School ID','Name of School','ZIP Code','Graduation Rate %', 'Ward','Average Student Attendance']]
schools_2011_df

,School ID,Name of School,ZIP Code,Graduation Rate %,Ward,Average Student Attendance
8,609680,Walter Payton College Preparatory High School,60610,96.9,27,93.4
15,609722,Manley Career Academy High School,60612,49,28,66.8
17,609749,Northside College Preparatory High School,60625,97.6,40,95.7
28,610244,Michele Clark Academic Prep Magnet High School,60644,87.4,24,79.1
30,610394,Uplift Community High School,60640,62.4,46,88.7
...,...,...,...,...,...,...
554,609753,Chicago High School for Agricultural Sciences,60655,70.7,19,92.8
559,609724,Stephen T Mather High School,60659,56.2,40,87.6
560,610297,High School of Leadership at South Shore,60649,36.6,8,72.0
561,610506,TEAM Englewood Community Academy High School,60621,NDA,20,87.3
564,610384,Infinity Math Science and Technology High School,60623,84.4,22,92.2

In [7]:
csv_path_2 = os.path.join("chi_school_2015_2016.csv")
schools_2015_df = pd.read_csv(csv_path_1, encoding="utf-8")
schools_2015_df.head()

,School ID,Name of School,"Elementary, Middle, or High School",Street Address,City,State,ZIP Code,Phone Number,Link,Network Manager,...,RCDTS Code,X_COORDINATE,Y_COORDINATE,Latitude,Longitude,Community Area Number,Community Area Name,Ward,Police District,Location
0,609966,Charles G Hammond Elementary School,ES,2819 W 21st Pl,Chicago,IL,60623,(773) 535-4580,http://schoolreports.cps.edu/SchoolProgressRep...,Pilsen-Little Village Elementary Network,...,150000000000000,1157809.015,1889554.623,41.852691,-87.696278,30,SOUTH LAWNDALE,12,10,"(41.85269133, -87.69627777)"
1,610539,Marvin Camras Elementary School,ES,3000 N Mango Ave,Chicago,IL,60634,(773) 534-2960,http://schoolreports.cps.edu/SchoolProgressRep...,Fullerton Elementary Network,...,150000000000000,1137482.296,1919394.900,41.934966,-87.770165,19,BELMONT CRAGIN,30,25,"(41.93496641, -87.77016525)"
2,609852,Eliza Chappell Elementary School,ES,2135 W Foster Ave,Chicago,IL,60625,(773) 534-2390,http://schoolreports.cps.edu/SchoolProgressRep...,Ravenswood-Ridge Elementary Network,...,150000000000000,1161016.902,1934466.545,41.975867,-87.683254,4,LINCOLN SQUARE,47,20,"(41.975867, -87.68325438)"
3,609835,Daniel R Cameron Elementary School,ES,1234 N Monticello Ave,Chicago,IL,60651,(773) 534-4290,http://schoolreports.cps.edu/SchoolProgressRep...,Garfield-Humboldt Elementary Network,...,150000000000000,1151767.546,1908130.068,41.903785,-87.717963,23,HUMBOLDT PARK,26,25,"(41.90378521, -87.71796315)"
4,610521,Sir Miles Davis Magnet Elementary Academy,ES,6730 S Paulina St,Chicago,IL,60636,(773) 535-9120,http://schoolreports.cps.edu/SchoolProgressRep...,Englewood-Gresham Elementary Network,...,150000000000000,1166133.893,1859929.018,41.771222,-87.666567,67,WEST ENGLEWOOD,15,7,"(41.77122181, -87.66656657)"

In [44]:
schools_2015_df = schools_2015_df[['School ID','Name of School','ZIP Code','Elementary, Middle, or High School','Graduation Rate %', 'Ward','Average Student Attendance']]

In [45]:
schools_2015_df = schools_2015_df[schools_2015_df['Elementary, Middle, or High School'] == "HS"]
schools_2015_df = schools_2015_df[['School ID','Name of School','ZIP Code','Graduation Rate %', 'Ward','Average Student Attendance']]
schools_2015_df

,School ID,Name of School,ZIP Code,Graduation Rate %,Ward,Average Student Attendance
8,609680,Walter Payton College Preparatory High School,60610,96.9,27,93.4
15,609722,Manley Career Academy High School,60612,49,28,66.8
17,609749,Northside College Preparatory High School,60625,97.6,40,95.7
28,610244,Michele Clark Academic Prep Magnet High School,60644,87.4,24,79.1
30,610394,Uplift Community High School,60640,62.4,46,88.7
...,...,...,...,...,...,...
554,609753,Chicago High School for Agricultural Sciences,60655,70.7,19,92.8
559,609724,Stephen T Mather High School,60659,56.2,40,87.6
560,610297,High School of Leadership at South Shore,60649,36.6,8,72.0
561,610506,TEAM Englewood Community Academy High School,60621,NDA,20,87.3
564,610384,Infinity Math Science and Technology High School,60623,84.4,22,92.2

In [6]:
csv_path_3 = os.path.join("chi_school_2020_2021.csv")
schools_2020_df = pd.read_csv(csv_path_1, encoding="utf-8")
schools_2020_df.head()

,School ID,Name of School,"Elementary, Middle, or High School",Street Address,City,State,ZIP Code,Phone Number,Link,Network Manager,...,RCDTS Code,X_COORDINATE,Y_COORDINATE,Latitude,Longitude,Community Area Number,Community Area Name,Ward,Police District,Location
0,609966,Charles G Hammond Elementary School,ES,2819 W 21st Pl,Chicago,IL,60623,(773) 535-4580,http://schoolreports.cps.edu/SchoolProgressRep...,Pilsen-Little Village Elementary Network,...,150000000000000,1157809.015,1889554.623,41.852691,-87.696278,30,SOUTH LAWNDALE,12,10,"(41.85269133, -87.69627777)"
1,610539,Marvin Camras Elementary School,ES,3000 N Mango Ave,Chicago,IL,60634,(773) 534-2960,http://schoolreports.cps.edu/SchoolProgressRep...,Fullerton Elementary Network,...,150000000000000,1137482.296,1919394.900,41.934966,-87.770165,19,BELMONT CRAGIN,30,25,"(41.93496641, -87.77016525)"
2,609852,Eliza Chappell Elementary School,ES,2135 W Foster Ave,Chicago,IL,60625,(773) 534-2390,http://schoolreports.cps.edu/SchoolProgressRep...,Ravenswood-Ridge Elementary Network,...,150000000000000,1161016.902,1934466.545,41.975867,-87.683254,4,LINCOLN SQUARE,47,20,"(41.975867, -87.68325438)"
3,609835,Daniel R Cameron Elementary School,ES,1234 N Monticello Ave,Chicago,IL,60651,(773) 534-4290,http://schoolreports.cps.edu/SchoolProgressRep...,Garfield-Humboldt Elementary Network,...,150000000000000,1151767.546,1908130.068,41.903785,-87.717963,23,HUMBOLDT PARK,26,25,"(41.90378521, -87.71796315)"
4,610521,Sir Miles Davis Magnet Elementary Academy,ES,6730 S Paulina St,Chicago,IL,60636,(773) 535-9120,http://schoolreports.cps.edu/SchoolProgressRep...,Englewood-Gresham Elementary Network,...,150000000000000,1166133.893,1859929.018,41.771222,-87.666567,67,WEST ENGLEWOOD,15,7,"(41.77122181, -87.66656657)"

In [46]:
schools_2020_df = schools_2020_df[['School ID','Name of School','ZIP Code','Elementary, Middle, or High School','Graduation Rate %', 'Ward','Average Student Attendance']]
schools_2020_df = schools_2020_df[schools_2020_df['Elementary, Middle, or High School'] == "HS"]
schools_2020_df = schools_2020_df[['School ID','Name of School','ZIP Code','Graduation Rate %', 'Ward','Average Student Attendance']]
schools_2020_df

,School ID,Name of School,ZIP Code,Graduation Rate %,Ward,Average Student Attendance
8,609680,Walter Payton College Preparatory High School,60610,96.9,27,93.4
15,609722,Manley Career Academy High School,60612,49,28,66.8
17,609749,Northside College Preparatory High School,60625,97.6,40,95.7
28,610244,Michele Clark Academic Prep Magnet High School,60644,87.4,24,79.1
30,610394,Uplift Community High School,60640,62.4,46,88.7
...,...,...,...,...,...,...
554,609753,Chicago High School for Agricultural Sciences,60655,70.7,19,92.8
559,609724,Stephen T Mather High School,60659,56.2,40,87.6
560,610297,High School of Leadership at South Shore,60649,36.6,8,72.0
561,610506,TEAM Englewood Community Academy High School,60621,NDA,20,87.3
564,610384,Infinity Math Science and Technology High School,60623,84.4,22,92.2

## Append Zip Code to Lat/Lng

In [2]:
# Import the CSV data for the clean crime data
csv_path_2 = os.path.join("crimes_2011_clean.csv")
crime_df = pd.read_csv(csv_path_2, encoding="utf-8")
crime_df.head()

,Unnamed: 0,Primary Type,Description,Latitude,Longitude
0,0,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,41.747362,-87.708424
1,3,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,41.891766,-87.766554
2,4,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,41.895419,-87.766632
3,6,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,41.875944,-87.743451
4,7,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,41.987282,-87.787652

In [5]:
# Add column for Zip Code
crime_df['Zip Code'] = ""
crime_df.head()

,Unnamed: 0,Primary Type,Description,Latitude,Longitude,Zip Code
0,0,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,41.747362,-87.708424,
1,3,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,41.891766,-87.766554,
2,4,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,41.895419,-87.766632,
3,6,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,41.875944,-87.743451,
4,7,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,41.987282,-87.787652,

In [31]:
# Perform Geocode lookup to pull zip code from the Lat/Long data
base_url = "https://maps.googleapis.com/maps/api/geocode/json?"
lat = 0
lng = 0
API_key = "AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8"

from pprint import pprint

query_url = f"{base_url}latlng={lat},{lng}&key={API_key}"
print(query_url)

https://maps.googleapis.com/maps/api/geocode/json?latlng=0,0&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8

In [39]:
# Run though the rows in the Crimes DataFrame and add the zip code to the Lat/Lng based on the geocode lookup

for index, row in crime_df.iloc[:100].iterrows():
    
    #Define the Latitude and Longitude for the API call
    lat = row['Latitude']
    lng = row['Longitude']
    print(lat, lng)

    # Create query string for API call
    query_url = f"{base_url}latlng={lat},{lng}&key={API_key}"
    print(query_url)

    # Call geocode to get resopnse json based on the inputs of latitude, longitude and API key
    response_json = requests.get(query_url).json()

    #pprint(response_json) - USED JUST TO CHECK RESPONSE
    try:
        zip_code = response_json['results'][0]['address_components'][7]['long_name']
        print(zip_code)
        crime_df.loc[index, 'Zip Code'] = zip_code
    except (KeyError, IndexError):
        print(f"Error on index {index}.")

41.747362057 -87.708423712
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.747362057,-87.708423712&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60652
41.891765632 -87.766553683
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.891765632,-87.766553683&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60644
41.895418606 -87.766631575
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.895418606,-87.766631575&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60651
41.875943951 -87.743450627
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.875943951,-87.743450627&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60644
41.987281741 -87.787651678
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.987281741,-87.787651678&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60646
41.765152708 -87.56649425
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.765152708,-87.56649425&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60649
41.869630875 -87.719636603
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.869630875,-87.719636603&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60624
41.75310285 -87.550270556
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.75310285,-87.550270556&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60649
41.773261385 -87.593591924
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.773261385,-87.593591924&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60637
41.756917825 -87.58914335
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.756917825,-87.58914335&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60619
41.879332837 -87.758551992
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.879332837,-87.758551992&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60644
41.899303534 -87.758167238
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.899303534,-87.758167238&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60651
41.71003614 -87.665887697
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.71003614,-87.665887697&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60643
41.94376138 -87.683319284
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.94376138,-87.683319284&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60618
41.938866781 -87.744028854
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.938866781,-87.744028854&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60641
41.81602778 -87.723883074
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.81602778,-87.723883074&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
Error on index 15.
41.928672868 -87.75717954
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.928672868,-87.75717954&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60639
41.776314836 -87.757874309
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.776314836,-87.757874309&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60638
41.739663786 -87.584403429
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.739663786,-87.584403429&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60617
41.751397971 -87.701223651
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.751397971,-87.701223651&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60652
41.879272306 -87.642941847
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.879272306,-87.642941847&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60661
41.817985681 -87.609215318
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.817985681,-87.609215318&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60653
41.836296774 -87.640578349
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.836296774,-87.640578349&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60616
41.769231153 -87.569854828
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.769231153,-87.569854828&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60649
41.879766808 -87.771382019
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.879766808,-87.771382019&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60644
41.76465077 -87.686043036
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.76465077,-87.686043036&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60629
41.878373528 -87.762640179
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.878373528,-87.762640179&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60644
41.704075384 -87.628193565
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.704075384,-87.628193565&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60628
41.907153315 -87.639680572
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.907153315,-87.639680572&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60610
41.871777415 -87.714112315
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.871777415,-87.714112315&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60624
41.793570812 -87.700446407
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.793570812,-87.700446407&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
Error on index 30.
41.764293941 -87.708838587
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.764293941,-87.708838587&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60629
41.671673989 -87.633287278
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.671673989,-87.633287278&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60628
41.948331123 -87.644366037
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.948331123,-87.644366037&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60613
41.710102632 -87.640491947
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.710102632,-87.640491947&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60628
41.992738481 -87.698256423
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.992738481,-87.698256423&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60659
41.87980954 -87.721738795
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.87980954,-87.721738795&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60624
41.924630138 -87.714883963
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.924630138,-87.714883963&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60647
41.971605914 -87.768174187
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.971605914,-87.768174187&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60630
41.699001218 -87.626868514
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.699001218,-87.626868514&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60628
41.724125806 -87.654232142
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.724125806,-87.654232142&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60620
41.789191206 -87.700995519
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.789191206,-87.700995519&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60629
41.853996428 -87.676880448
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.853996428,-87.676880448&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60608
41.779937137 -87.607183409
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.779937137,-87.607183409&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60637
41.818647053 -87.685983816
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.818647053,-87.685983816&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60632
41.679187566 -87.635925711
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.679187566,-87.635925711&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60628
41.99373453 -87.67533977
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.99373453,-87.67533977&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60660
41.755366724 -87.565698177
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.755366724,-87.565698177&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60649
41.706682551 -87.663054879
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.706682551,-87.663054879&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60643
41.817686987 -87.624685155
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.817686987,-87.624685155&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60653
41.929720595 -87.785661946
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.929720595,-87.785661946&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60639
41.898457758 -87.662467348
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.898457758,-87.662467348&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60642
41.806582764 -87.622764529
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.806582764,-87.622764529&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60615
41.871852149 -87.639346414
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.871852149,-87.639346414&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
Error on index 53.
41.939290467 -87.658952119
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.939290467,-87.658952119&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60657
41.898083254 -87.727393715
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.898083254,-87.727393715&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60651
41.748075479 -87.656101572
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.748075479,-87.656101572&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60620
41.87974804 -87.726700354
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.87974804,-87.726700354&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60624
41.788725276 -87.73650278
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.788725276,-87.73650278&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60629
41.900527561 -87.671088866
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.900527561,-87.671088866&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60622
41.768610883 -87.659800625
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.768610883,-87.659800625&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60636
41.970298975 -87.705205096
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.970298975,-87.705205096&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60625
41.909855173 -87.771478233
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.909855173,-87.771478233&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60639
41.909490571 -87.756609961
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.909490571,-87.756609961&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60639
41.914381631 -87.763925077
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.914381631,-87.763925077&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60639
42.012220854 -87.684274879
https://maps.googleapis.com/maps/api/geocode/json?latlng=42.012220854,-87.684274879&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60645
41.857016848 -87.726599538
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.857016848,-87.726599538&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60623
41.945781892 -87.645305097
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.945781892,-87.645305097&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60657
41.902041291 -87.731205967
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.902041291,-87.731205967&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60651
41.816647898 -87.616002363
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.816647898,-87.616002363&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60653
41.744989508 -87.65680092
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.744989508,-87.65680092&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60620
41.787020592 -87.712083182
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.787020592,-87.712083182&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60629
41.720023208 -87.576514422
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.720023208,-87.576514422&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60617
41.778545198 -87.690940817
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.778545198,-87.690940817&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60629
41.876709653 -87.750989346
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.876709653,-87.750989346&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60644
41.78051046 -87.659386469
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.78051046,-87.659386469&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60636
41.901170711 -87.771693958
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.901170711,-87.771693958&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60651
41.771910205 -87.687641714
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.771910205,-87.687641714&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60629
41.857533855 -87.625603607
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.857533855,-87.625603607&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60616
41.917678861 -87.755963058
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.917678861,-87.755963058&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60639
41.807822931 -87.660083294
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.807822931,-87.660083294&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60609
41.790196981 -87.642615048
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.790196981,-87.642615048&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60621
41.877005438 -87.681425861
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.877005438,-87.681425861&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60612
41.763260042 -87.606744693
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.763260042,-87.606744693&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60619
41.748838927 -87.612437207
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.748838927,-87.612437207&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60619
41.777676745 -87.723956682
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.777676745,-87.723956682&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60629
41.854498094 -87.723580391
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.854498094,-87.723580391&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60623
41.749885207 -87.625794162
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.749885207,-87.625794162&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60620
41.794550978 -87.70603292
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.794550978,-87.70603292&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60632
41.814982676 -87.690734573
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.814982676,-87.690734573&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60632
41.908606347 -87.625954515
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.908606347,-87.625954515&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60614
41.781217946 -87.764294424
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.781217946,-87.764294424&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60638
41.956942374 -87.757983811
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.956942374,-87.757983811&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60641
41.883869155 -87.746627731
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.883869155,-87.746627731&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60644
41.810289998 -87.61962035
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.810289998,-87.61962035&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60653
41.803417249 -87.585796054
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.803417249,-87.585796054&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60615
41.766565077 -87.638385555
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.766565077,-87.638385555&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60621
41.666563743 -87.628302922
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.666563743,-87.628302922&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60628
41.822199933 -87.602134797
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.822199933,-87.602134797&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60653
41.877169004 -87.719061434
https://maps.googleapis.com/maps/api/geocode/json?latlng=41.877169004,-87.719061434&key=AIzaSyApC6RKbQX-oTKm-pSdntYAAGKXw8se1h8
60624

In [40]:
crime_df.head()

,Unnamed: 0,Primary Type,Description,Latitude,Longitude,Zip Code
0,0,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,41.747362,-87.708424,60652
1,3,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,41.891766,-87.766554,60644
2,4,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,41.895419,-87.766632,60651
3,6,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,41.875944,-87.743451,60644
4,7,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,41.987282,-87.787652,60646