In [3]:
import pandas as pd

In [8]:
# File to Load (Remember to Change These)
file_to_load = "Resources/Crimes_-_2015.csv"

# Read Purchasing File and store into Pandas data frame
df = pd.read_csv(file_to_load)

crimes_2015 = df[["Primary Type", "Description","Latitude","Longitude"]]
crimes_2015 = crimes_2015.dropna()
crimes_2015.to_csv('crimes_2015_clean.csv',encoding='utf-8')
crimes_2015

,Primary Type,Description,Latitude,Longitude
0,BATTERY,DOMESTIC BATTERY SIMPLE,41.815117,-87.670000
1,THEFT,POCKET-PICKING,41.895080,-87.765400
2,NARCOTICS,POSS: HEROIN(BRN/TAN),41.937406,-87.716650
3,ASSAULT,SIMPLE,41.881903,-87.755121
4,BURGLARY,FORCIBLE ENTRY,41.744379,-87.658431
...,...,...,...,...
264610,OTHER OFFENSE,OTHER VEHICLE OFFENSE,41.910395,-87.756914
264611,BATTERY,AGGRAVATED DOMESTIC BATTERY - KNIFE / CUTTING ...,41.949434,-87.809568
264612,BATTERY,AGGRAVATED - HANDGUN,41.903199,-87.751807
264613,BATTERY,AGGRAVATED - HANDGUN,41.907739,-87.751611
264616,CRIMINAL SEXUAL ASSAULT,PREDATORY,41.892005,-87.760536

In [25]:
df

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,10224738,HY411648,09/05/2015 01:30:00 PM,043XX S WOOD ST,0486,BATTERY,DOMESTIC BATTERY SIMPLE,RESIDENCE,False,True,...,12.0,61,08B,1165074.0,1875917.0,2015,02/10/2018 03:50:01 PM,41.815117,-87.670000,"(41.815117282, -87.669999562)"
1,10224739,HY411615,09/04/2015 11:30:00 AM,008XX N CENTRAL AVE,0870,THEFT,POCKET-PICKING,CTA BUS,False,False,...,29.0,25,06,1138875.0,1904869.0,2015,02/10/2018 03:50:01 PM,41.895080,-87.765400,"(41.895080471, -87.765400451)"
2,10224740,HY411595,09/05/2015 12:45:00 PM,035XX W BARRY AVE,2023,NARCOTICS,POSS: HEROIN(BRN/TAN),SIDEWALK,True,False,...,35.0,21,18,1152037.0,1920384.0,2015,02/10/2018 03:50:01 PM,41.937406,-87.716650,"(41.937405765, -87.716649687)"
3,10224741,HY411610,09/05/2015 01:00:00 PM,0000X N LARAMIE AVE,0560,ASSAULT,SIMPLE,APARTMENT,False,True,...,28.0,25,08A,1141706.0,1900086.0,2015,02/10/2018 03:50:01 PM,41.881903,-87.755121,"(41.881903443, -87.755121152)"
4,10224742,HY411435,09/05/2015 10:55:00 AM,082XX S LOOMIS BLVD,0610,BURGLARY,FORCIBLE ENTRY,RESIDENCE,False,False,...,21.0,71,05,1168430.0,1850165.0,2015,02/10/2018 03:50:01 PM,41.744379,-87.658431,"(41.744378879, -87.658430635)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
264613,10285653,HY473027,10/23/2015 09:06:00 AM,050XX W LE MOYNE ST,041A,BATTERY,AGGRAVATED - HANDGUN,SIDEWALK,False,False,...,37.0,25,04B,1142598.0,1909507.0,2015,01/26/2022 03:51:49 PM,41.907739,-87.751611,"(41.907739231, -87.75161115)"
264614,12602915,JF124797,01/01/2015 12:00:00 AM,047XX S AVERS AVE,1563,SEX OFFENSE,CRIMINAL SEXUAL ABUSE,RESIDENCE,False,False,...,14.0,57,17,NaN,NaN,2015,01/28/2022 03:48:18 PM,NaN,NaN,NaN
264615,12604086,JF127006,05/01/2015 07:30:00 AM,099XX S LOWE AVE,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,NaN,False,False,...,9.0,73,11,NaN,NaN,2015,01/29/2022 03:49:20 PM,NaN,NaN,NaN
264616,10157910,HY347082,07/17/2015 06:00:00 PM,006XX N LONG AVE,0266,CRIMINAL SEXUAL ASSAULT,PREDATORY,RESIDENCE,False,False,...,37.0,25,02,1140207.0,1903757.0,2015,02/01/2022 03:51:55 PM,41.892005,-87.760536,"(41.892004708, -87.760535556)"
264617,12605907,JF129452,02/25/2015 09:00:00 AM,022XX N KILBOURN AVE,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,APARTMENT,False,False,...,36.0,20,11,NaN,NaN,2015,02/01/2022 03:54:31 PM,NaN,NaN,NaN