In [3]:
import pandas as pd

In [8]:
# File to Load (Remember to Change These)
file_to_load = "Resources/Crimes_-_2015.csv"

# Read Purchasing File and store into Pandas data frame
df = pd.read_csv(file_to_load)

crimes_2015 = df[["Primary Type", "Description","Latitude","Longitude"]]
crimes_2015 = crimes_2015.dropna()
crimes_2015.to_csv('crimes_2015_clean.csv',encoding='utf-8')
crimes_2015

,Primary Type,Description,Latitude,Longitude
0,BATTERY,DOMESTIC BATTERY SIMPLE,41.815117,-87.670000
1,THEFT,POCKET-PICKING,41.895080,-87.765400
2,NARCOTICS,POSS: HEROIN(BRN/TAN),41.937406,-87.716650
3,ASSAULT,SIMPLE,41.881903,-87.755121
4,BURGLARY,FORCIBLE ENTRY,41.744379,-87.658431
...,...,...,...,...
264610,OTHER OFFENSE,OTHER VEHICLE OFFENSE,41.910395,-87.756914
264611,BATTERY,AGGRAVATED DOMESTIC BATTERY - KNIFE / CUTTING ...,41.949434,-87.809568
264612,BATTERY,AGGRAVATED - HANDGUN,41.903199,-87.751807
264613,BATTERY,AGGRAVATED - HANDGUN,41.907739,-87.751611
264616,CRIMINAL SEXUAL ASSAULT,PREDATORY,41.892005,-87.760536

In [10]:
# File to Load (Remember to Change These)
file_to_load = "Resources/Crimes_-_2011.csv"

# Read Purchasing File and store into Pandas data frame
df = pd.read_csv(file_to_load)

crimes_2011 = df[["Primary Type", "Description","Latitude","Longitude"]]
crimes_2011 = crimes_2011.dropna()
crimes_2011.to_csv('crimes_2021_clean.csv',encoding='utf-8')
crimes_2011

,Primary Type,Description,Latitude,Longitude
0,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,41.747362,-87.708424
3,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,41.891766,-87.766554
4,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,41.895419,-87.766632
6,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,41.875944,-87.743451
7,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,41.987282,-87.787652
...,...,...,...,...
351926,BATTERY,AGGRAVATED POLICE OFFICER - OTHER DANGEROUS WE...,41.880642,-87.706113
351929,ASSAULT,AGGRAVATED - HANDGUN,41.854086,-87.644457
351930,OFFENSE INVOLVING CHILDREN,AGGRAVATED SEXUAL ASSAULT OF CHILD BY FAMILY M...,41.806062,-87.673412
351931,OTHER OFFENSE,VIOLATE ORDER OF PROTECTION,41.898807,-87.671037
351932,BATTERY,DOMESTIC BATTERY SIMPLE,41.899705,-87.723771

In [ ]:
# File to Load (Remember to Change These)
file_to_load = "Resources/Crimes_-_2021.csv"

# Read Purchasing File and store into Pandas data frame
df = pd.read_csv(file_to_load)

crimes_2021 = df[["Primary Type", "Description","Latitude","Longitude"]]
crimes_2021 = crimes_2021.dropna()
crimes_2021.to_csv('crimes_2021_clean.csv',encoding='utf-8')
crimes_2021